### PR TITLE
fix #57 test requirements and CI tests pull brightway2

### LINKED ISSUE #57: test requirements and CI tests pull brightway2
Current  [requirements-test.txt](https://github.com/brightway-lca/brightway2-calc/blob/770cb83954499199888bb7422442cbdc7ef553b3/requirements-test.txt) includes [brightway2](github.com/brightway-lca/brightway2):

```
brightway2
bw_processing
numpy
pandas
pytest
pytest-cov
python-coveralls
scipy
stats_arrays
```
The [azure-pipelines](https://github.com/brightway-lca/brightway2-calc/blob/770cb83954499199888bb7422442cbdc7ef553b3/azure-pipelines.yml) install testing deps by hand:

(for ubuntu 20.04 )
```
conda install --yes --quiet -c defaults -c conda-forge -c cmutel -c haasad --name bw2 python=$PYTHON_VERSION numpy bw_processing matrix_utils pandas scipy psutil pypardiso pytest peewee brightway2 pytest pytest-azurepipelines">=1.0.2" pytest-cov
```

this _mix_ ( ;) ), from the master branch of brightway2-calc will lead to testing using other brightway2 packages that might not be suited for brightway25 environment.

- [ ] Is testing the master branch supposed to represent testing bw2calc for brightway25 ?
- [ ] Are bw2calc and bw2data master branches + releases (2.0 and 4.0 respectiveley) supposed to work together under brightway25 ?

### PR DESCRIPTION
**Pull request by tngTUDOR**
merging this **might need a version bump** (_not included in the commit_).

### CODE REVIEW

**Comment by tngTUDOR** [comment]
this is in reference to issue #57

**Comment by tngTUDOR** [comment]
If this pipeline definition with azure succeeds, it could also be tested in relation to [bw2calc issue 55](https://github.com/brightway-lca/brightway2-calc/issues/55)

**Comment by cmutel** [comment]
This is amazing! I have been unable to understand why the pip tests weren't working, and of course it is a dumb, simple error.

However, I removed `bw2calc` from `setup.py` and `requirements.txt` on purpose - `bw2calc` should be usable without the rest of the ecosystem. Can you update the PR, it will be easier than me having to do it :)

**Comment by tngTUDOR** [comment]
> This is amazing! I have been unable to understand why the pip tests weren't working, and of course it is a dumb, simple error.
> 
> However, I removed `bw2calc` from `setup.py` and `requirements.txt` on purpose - `bw2calc` should be usable without the rest of the ecosystem. Can you update the PR, it will be easier than me having to do it :)

Did you mean `bw2data` ?

I'll work this out.

**Comment by tngTUDOR** [comment]
removing `bw2data` from setup.py breaks the package:
with:

```python3
...
install_requires=[
"bw_processing",
"matrix_utils",
"numpy",
"pandas",
"scipy",
"stats_arrays",
],
...
```

```python3
>>> import bw2calc as bc
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/code/bw2calc/__init__.py", line 55, in <module>
from .multi_lca import MultiLCA
File "/code/bw2calc/multi_lca.py", line 2, in <module>
from bw2data import calculation_setups
ModuleNotFoundError: No module named 'bw2data'
```

I'll revert the changes to setup.py and requirements and create a separate issue for this. -> issue #60

**Comment by tngTUDOR** [comment]
The solution for the pipelines to pass was to use a virtualenv for the ubuntu-20.04-pip based testing env.

**Comment by tngTUDOR** [comment]
@cmutel , I did not add a version bmp to the PR, and I decided to keep the bw2data dependency because otherwise, the package would be broken (see comment above).

#60 has the issue explaining why we cannot remove bw2data from deps (MultiLCA needs it)

I think we can merge this, without releasing, then update MultiLCA to not depend on bw2data [if at all possible] and then do the bump.

**Pull request merged**
